sudo: required
services:
  - docker

before_install:
  - docker build -t reddyshack/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true reddyshack/react-test npm run test

after_success:
  - docker build -t reddyshack/multi-client ./client
  - docker build -t reddyshack/multi-nginx ./nginx
  - docker build -t reddyshack/multi-server ./server
  - docker build -t reddyshack/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to dockerhub
  - docker push reddyshack/multi-client
  - docker push reddyshack/multi-nginx
  - docker push reddyshack/multi-server
  - docker push reddyshack/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-301626332286
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY